version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/connect/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/integration/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/test-utils/"
    schedule:
      interval: "weekly"