#
# Copyright (C) 2022-2024 Confluent, Inc.
#

name: kafka-client-smart-ser-des
lang: java
lang_version: unknown
git:
  enable: true
github:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  tasks:
    - name: release
      branch: main
      pipeline_file: ".semaphore/release.yml"
      parameters:
        - name: PROJECT_VERSION
          required: true
          default_value: "X.Y.Z"
        - name: NEXT_PROJECT_VERSION
          required: true
          default_value: "X.Y.Z-SNAPSHOT"
  managed_sections:
    - version
    - name
    - agent
    - global_job_config
make:
  enable: true
  enable_updates: true
  update_makefile: false
code_artifact:
  enable: true
  package_paths:
    - maven-releases/maven/io.confluent/kafka-client-smart-integration
    - maven-releases/maven/io.confluent/kafka-client-smart-connect
    - maven-releases/maven/io.confluent/kafka-client-smart-deserializer
    - maven-releases/maven/io.confluent/kafka-client-smart-serializer
    - maven-releases/maven/io.confluent/kafka-client-smart-common
    - maven-releases/maven/io.confluent/kafka-client-smart-test-utils
    - maven-releases/maven/io.confluent/kafka-client-smart-ser-des
