#
# Copyright (C) 2022-2024 Confluent, Inc.
#

name: data-stream-composer-ser-des
lang: java
lang_version: unknown
git:
  enable: true
github:
  enable: true
semaphore:
  enable: true
  pipeline_enable: false
  tasks:
    - name: release
      branch: main
      pipeline_file: ".semaphore/release.yml"
      parameters:
        - name: PROJECT_VERSION
          required: true
          default_value: "X.Y.Z"
        - name: NEXT_PROJECT_VERSION
          required: true
          default_value: "X.Y.Z-SNAPSHOT"
make:
  enable: true
  enable_updates: true
  update_makefile: false
code_artifact:
  enable: true
  package_paths:
    - maven-releases/maven/io.confluent/data-stream-composer-ser-des-integration
    - maven-releases/maven/io.confluent/data-stream-composer-connect
    - maven-releases/maven/io.confluent/data-stream-composer-deserializer
    - maven-releases/maven/io.confluent/data-stream-composer-serializer
    - maven-releases/maven/io.confluent/data-stream-composer-ser-des-common
    - maven-releases/maven/io.confluent/data-stream-composer-test-utils
    - maven-releases/maven/io.confluent/data-stream-composer-ser-des
